/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPresentation.Dashboard.users;

import DataAccess.AuthAndRegister.Register;
import DataAccess.Responses.BadResponse;
import com.google.gson.Gson;
import com.google.gson.JsonSyntaxException;
import java.awt.BorderLayout;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author braya
 */
public class VerifyScheduleUI extends javax.swing.JPanel {

    private String token, names, type;
    /**
     * Creates new form VerifyScheduleUI
     * @param token
     */
    public VerifyScheduleUI(String token) {
        this.token = token;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSchedule = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNames = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcbType = new javax.swing.JComboBox<>();
        btnRegister = new javax.swing.JButton();

        jLabel1.setText("Cédula o RUC:");

        jLabel2.setText("Nombres:");

        txtNames.setEnabled(false);

        jLabel3.setText("Correo electrónico:");

        txtemail.setEnabled(false);

        jLabel4.setText("Tipo de Usuario:");

        jcbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Administrador", "Usuario" }));
        jcbType.setEnabled(false);
        jcbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTypeActionPerformed(evt);
            }
        });

        btnRegister.setText("Verificar Usuario");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txtSchedule)
                    .addComponent(txtNames)
                    .addComponent(txtemail)
                    .addComponent(jcbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(txtSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegister)
                .addContainerGap(187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String textButton = btnRegister.getText();
        if("Verificar Usuario".equals(textButton)){
            //Recogemos los datos de la schedule
            String schedule = txtSchedule.getText();
            Register petition = new Register(schedule);
            Gson gson = new Gson();
            String jsonObject = gson.toJson(petition);
            try {            
                String response = petition.verifySchedule(jsonObject, this.token);
                if(response == null){
                    //Se cierra el programa porque es incorrecto
                    JOptionPane.showMessageDialog(this, "Tu sesión ha terminado, vuelve a iniciar el programa para seguir");
                    System.exit(0);
                }
                else{
                    //Transformamos el json a java object
                    Register javaobj = new Gson().fromJson(response, Register.class);
                    this.names = javaobj.getNombre();
                    //Hacemos cambios en la parte grafica
                    txtSchedule.setEnabled(false);
                    txtNames.setText(this.names);
                    txtemail.setEnabled(true);
                    jcbType.setEnabled(true);
                    btnRegister.setText("Registrar Usuario");
                    btnRegister.setEnabled(false);
                    JOptionPane.showMessageDialog(this, "Usuario verificado satisfactoriamente");
                }
                
            } catch (InterruptedException | IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            } catch (JsonSyntaxException ex) {
               //Aquí captura si un error es negativo
                BadResponse response = new Gson().fromJson(ex.getMessage(), BadResponse.class);
                JOptionPane.showMessageDialog(this, response.getMessage());
            } 
            
        }
        else{
            
            //Recogemos los datos del registro y los convertimos en json
            String schedule = txtSchedule.getText();
            String email = txtemail.getText();
            Register request = new Register(this.names, email, schedule, this.type);
            Gson gson = new Gson();
            String jsonObject = gson.toJson(request);
            //JOptionPane.showMessageDialog(this, jsonObject);
            
            try {            
                String response = request.registerUser(jsonObject, this.token);
                if(response == null){
                    //Se cierra el programa porque es incorrecto
                    JOptionPane.showMessageDialog(this, "Tu sesión ha terminado, vuelve a iniciar el programa para seguir");
                    System.exit(0);
                }
                else{
                    JOptionPane.showMessageDialog(this, "El usuario ha sido registrado correctamente, comunicale que abra su correo para que valide su cuenta");
                    UsersPanelUI panelusers = new UsersPanelUI(this.token);
                    panelusers.setSize(814, 502);
                    this.removeAll();
                    this.add(panelusers, BorderLayout.CENTER);
                    this.revalidate();
                    this.repaint();
                    this.remove(this);
                }
                
            } catch (InterruptedException | IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            } catch (JsonSyntaxException ex) {
               //Aquí captura si un error es negativo
                BadResponse response = new Gson().fromJson(ex.getMessage(), BadResponse.class);
                JOptionPane.showMessageDialog(this, response.getMessage());
            }
            
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void jcbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTypeActionPerformed
        String selection = (String)jcbType.getSelectedItem();
       if("Administrador".equals(selection)){
            this.type = "true";
            btnRegister.setEnabled(true);
        }
        else if("Seleccione...".equals(selection)){
            btnRegister.setEnabled(false);
        }
        else{
            this.type = "false";
            btnRegister.setEnabled(true);
        }
    }//GEN-LAST:event_jcbTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> jcbType;
    private javax.swing.JTextField txtNames;
    private javax.swing.JTextField txtSchedule;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables
}
